config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  resources :notes
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy
  validates :title, presence: true
  validates :title, uniqueness: true

  scope :user_notes, ->(user) { where(['user_id = ?', user.id]) }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :note
  validates :title, :note, presence: true

  scope :user_tasks, ->(user) {joins(:note).where(['user_id = ?', user.id])}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end

    redirect_to root_path
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.user_notes(current_user)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.user = current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_note, only: [:new, :create]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.user_tasks(current_user)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @note.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @note.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.js   { flash[:notice] = 'Task was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  private
    def set_note
      @note = Note.find_by(id: params[:note_id]) || Note.find(task_params[:note_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:note_id, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')

= form_tag request_contact_path, method: 'post' do
  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size:50
  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')
  = label_tag :telephone, t('.telephone')
  = telephone_field_tag :telephone, '', title: t('.enter_telephone')
  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100
  = submit_tag t('.submit')

app/views/home/home.html.haml
%h1= t('.title')
%p= t('.welcome')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
    = render 'shared/header'
    = yield
    = render 'shared/footer'

app/views/notes/_form.html.haml
= form_for @note do |f|
  - if @note.errors.any?
    #error_explanation
      %h2= "#{pluralize(@note.errors.count, "error")} prohibited this note from being saved:"
      %ul
        - @note.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/notes/edit.html.haml
%h1 Editing note

= render 'form'

= link_to 'Show', @note
\|
= link_to 'Back', notes_path

app/views/notes/index.html.haml
%h1 Listing notes

%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th

  %tbody
    - @notes.each do |note|
      %tr
        %td= note.title
        %td= note.description
        %td= link_to 'Show', note
        %td= link_to 'Edit', edit_note_path(note)
        %td= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Note', new_note_path

app/views/notes/new.html.haml
%h1 New note

= render 'form'

= link_to 'Back', notes_path

app/views/notes/show.html.haml
%p
  %b Title:
  = @note.title
%p
  %b Description:
  = @note.description

%p Tasks:
%table
  %tbody
    - @note.tasks.each do |task|
      %tr{id: "task_#{task.id}"}
        %td= task.title
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?'}, :remote => true

%p= link_to 'Add Task', new_task_path(note_id: @note)


= link_to 'Edit', edit_note_path(@note)
\|
= link_to 'Back', notes_path

app/views/shared/_footer.html.haml
%footer
  %p!= "&copy; #{t('app_title')} #{Time.now.year}"

app/views/shared/_header.html.haml
%nav
  - if user_signed_in?
    = "#{current_user.email} |"
    = link_to t('profile'), edit_user_registration_path
    = '|'
    = link_to t('logout'), destroy_user_session_path, method: 'delete'
  - else
    = link_to t('login'), new_user_session_path
    = '|'
    = link_to t('sign_up'), new_user_registration_path

- flash.each do |key, value|
  = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :note
    %p= @task.note.title
    = f.text_field :note_id, value: @task.note.id
  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/tasks/destroy.js.erb
$('#task_<%= @task.id %>').hide();

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %thead
    %tr
      %th Note
      %th Title
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.note.title
        %td= task.title
        %td= link_to 'Show', task
        %td= link_to 'Edit', edit_task_path(task)
        %td= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p
  %b Note:
  = @task.note.title
%p
  %b Title:
  = @task.title

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path